export const CATEGORIAS = [
  {
    id: 1,
    nombre: "Suplementos",
    descripcion:
      "Suplementos deportivos para mejorar tu rendimiento y recuperación",
  },
  {
    id: 2,
    nombre: "Vitaminas",
    descripcion: "Vitaminas y minerales esenciales para tu salud",
  },
  {
    id: 3,
    nombre: "Accesorios",
    descripcion: "Accesorios para entrenamiento y organización",
  },
];

export const SUBCATEGORIAS = [
  // Suplementos
  { id: 1, nombre: "Proteínas", categoriaId: 1 },
  { id: 2, nombre: "Creatinas", categoriaId: 1 },
  { id: 3, nombre: "Ganadores de Masa", categoriaId: 1 },
  { id: 4, nombre: "Pre-Workout", categoriaId: 1 },
  { id: 5, nombre: "Aminoácidos", categoriaId: 1 },
  { id: 6, nombre: "Quemadores", categoriaId: 1 },
  { id: 7, nombre: "Hidratación", categoriaId: 1 },
  { id: 8, nombre: "Energía", categoriaId: 1 },

  // Vitaminas
  { id: 9, nombre: "Multivitamínicos", categoriaId: 2 },
  { id: 10, nombre: "Aceites Esenciales", categoriaId: 2 },
  { id: 11, nombre: "Vitaminas Individuales", categoriaId: 2 },
  { id: 12, nombre: "Minerales", categoriaId: 2 },
  { id: 13, nombre: "Adaptógenos", categoriaId: 2 },
  { id: 14, nombre: "Descanso", categoriaId: 2 },
  { id: 15, nombre: "Salud Articular", categoriaId: 2 },

  // Accesorios
  { id: 16, nombre: "Shakers", categoriaId: 3 },
  { id: 17, nombre: "Botellas", categoriaId: 3 },
  { id: 18, nombre: "Entrenamiento", categoriaId: 3 },
  { id: 19, nombre: "Cardio", categoriaId: 3 },
  { id: 20, nombre: "Higiene", categoriaId: 3 },
  { id: 21, nombre: "Bolsos", categoriaId: 3 },
  { id: 22, nombre: "Organización", categoriaId: 3 },
  { id: 23, nombre: "Recuperación", categoriaId: 3 },
];

export const MARCAS = [
  {
    id: 1,
    nombre: "Optimum Nutrition",
    descripcion: "Líder mundial en nutrición deportiva desde 1986",
    logo: "/images/marcas/optimum-nutrition-logo.png",
  },
  {
    id: 2,
    nombre: "Dymatize",
    descripcion: "Innovación y calidad en suplementos deportivos",
    logo: "/images/marcas/dymatize-logo.png",
  },
  {
    id: 3,
    nombre: "MuscleTech",
    descripcion: "Fórmulas científicamente probadas para atletas",
    logo: "/images/marcas/muscletech-logo.png",
  },
  {
    id: 4,
    nombre: "Garden of Life",
    descripcion: "Suplementos orgánicos y veganos certificados",
    logo: "/images/marcas/garden-of-life-logo.png",
  },
  {
    id: 5,
    nombre: "BSN",
    descripcion: "Performance y sabor excepcional desde 2001",
    logo: "/images/marcas/bsn-logo.png",
  },
  {
    id: 6,
    nombre: "Cellucor",
    descripcion: "Innovación en nutrición deportiva y pre-workouts",
    logo: "/images/marcas/cellucor-logo.png",
  },
];

export const DUMMY_PRODUCTS = [
  {
    id: 1,
    nombre: "Whey Protein Isolate Chocolate",
    descripcion:
      "Proteína de suero aislada de alta pureza con 90% de contenido proteico. Perfecta para la recuperación muscular post-entrenamiento. Baja en grasas y carbohidratos, ideal para definición muscular.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/whey-isolate-chocolate-1.jpg",
    imagenNutricional: "/images/nutricional/whey-isolate-chocolate-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 89.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 45,
  },
  {
    id: 2,
    nombre: "Whey Protein Isolate Vainilla",
    descripcion:
      "Proteína de suero aislada con delicioso sabor a vainilla. 25g de proteína por porción, absorción rápida y aminoácidos esenciales para máximo rendimiento.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/whey-isolate-vanilla-1.jpg",
    imagenNutricional: "/images/nutricional/whey-isolate-vanilla-nutri.jpg",
    marca: "Dymatize",
    precio: 89.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 32,
  },
  {
    id: 3,
    nombre: "Whey Protein Concentrate Fresa",
    descripcion:
      "Proteína concentrada de suero con excelente relación calidad-precio. 80% de proteína, perfecta para el crecimiento muscular y recuperación diaria.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/whey-concentrate-strawberry-1.jpg",
    imagenNutricional:
      "/images/nutricional/whey-concentrate-strawberry-nutri.jpg",
    marca: "MuscleTech",
    precio: 64.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 0,
  },
  {
    id: 4,
    nombre: "Proteína Vegana de Guisante y Arroz",
    descripcion:
      "Mezcla premium de proteína vegetal de guisante y arroz integral. 100% plant-based con perfil completo de aminoácidos. Sin lácteos, sin gluten, sin soja.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/vegan-protein-chocolate-1.jpg",
    imagenNutricional: "/images/nutricional/vegan-protein-chocolate-nutri.jpg",
    marca: "Garden of Life",
    precio: 79.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 28,
  },
  {
    id: 5,
    nombre: "Caseína Micelar Nocturna",
    descripcion:
      "Proteína de absorción lenta ideal para tomar antes de dormir. Liberación sostenida de aminoácidos durante 7-8 horas para recuperación muscular nocturna.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/casein-vanilla-1.jpg",
    imagenNutricional: "/images/nutricional/casein-vanilla-nutri.jpg",
    marca: "BSN",
    precio: 94.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 19,
  },
  {
    id: 6,
    nombre: "Creatina Monohidrato Micronizada",
    descripcion:
      "Creatina monohidrato 100% pura, micronizada para mejor absorción. 5g por porción. Aumenta fuerza, potencia y masa muscular magra. Sin sabor.",
    categoria: "Suplementos",
    subcategoria: "Creatinas",
    imagen: "/images/creatine-monohydrate-1.jpg",
    imagenNutricional: "/images/nutricional/creatine-monohydrate-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 39.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 67,
  },
  {
    id: 7,
    nombre: "Creatina HCL Avanzada",
    descripcion:
      "Clorhidrato de creatina de alta concentración. Requiere menor dosis que la monohidrato, sin retención de líquidos, sin fase de carga necesaria.",
    categoria: "Suplementos",
    subcategoria: "Creatinas",
    imagen: "/images/creatine-hcl-1.jpg",
    imagenNutricional: "/images/nutricional/creatine-hcl-nutri.jpg",
    marca: "Cellucor",
    precio: 54.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 41,
  },
  {
    id: 8,
    nombre: "Ganador de Masa Extreme 5000",
    descripcion:
      "Fórmula hipercalórica con 1250 calorías por porción. 50g de proteína, carbohidratos complejos, MCTs y creatina. Ideal para ectomorfos y bulking.",
    categoria: "Suplementos",
    subcategoria: "Ganadores de Masa",
    imagen: "/images/mass-gainer-chocolate-1.jpg",
    imagenNutricional: "/images/nutricional/mass-gainer-chocolate-nutri.jpg",
    marca: "MuscleTech",
    precio: 119.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 23,
  },
  {
    id: 9,
    nombre: "Ganador de Masa Lean Gainer",
    descripcion:
      "Ganador de masa magra con menor contenido calórico. 750 calorías por porción, 40g de proteína, carbohidratos de bajo índice glucémico.",
    categoria: "Suplementos",
    subcategoria: "Ganadores de Masa",
    imagen: "/images/lean-gainer-vanilla-1.jpg",
    imagenNutricional: "/images/nutricional/lean-gainer-vanilla-nutri.jpg",
    marca: "Dymatize",
    precio: 99.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 0,
  },
  {
    id: 10,
    nombre: "Ganador de Masa Vegano",
    descripcion:
      "Fórmula plant-based para aumento de masa muscular. 1100 calorías, 45g de proteína vegetal, carbohidratos de avena y quinoa. Sin lácteos ni soja.",
    categoria: "Suplementos",
    subcategoria: "Ganadores de Masa",
    imagen: "/images/vegan-mass-gainer-1.jpg",
    imagenNutricional: "/images/nutricional/vegan-mass-gainer-nutri.jpg",
    marca: "Garden of Life",
    precio: 129.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 12,
  },
  {
    id: 11,
    nombre: "Pre-Workout Explosive Energy",
    descripcion:
      "Pre-entreno con cafeína, beta-alanina, citrulina malato y taurina. Energía explosiva, mejor bombeo muscular y enfoque mental. Sabor frutas tropicales.",
    categoria: "Suplementos",
    subcategoria: "Pre-Workout",
    imagen: "/images/preworkout-tropical-1.jpg",
    imagenNutricional: "/images/nutricional/preworkout-tropical-nutri.jpg",
    marca: "Cellucor",
    precio: 49.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 54,
  },
  {
    id: 12,
    nombre: "BCAAs 2:1:1 Limón",
    descripcion:
      "Aminoácidos ramificados en proporción óptima 2:1:1. Previene el catabolismo muscular, acelera la recuperación. 5g por porción, sin azúcar.",
    categoria: "Suplementos",
    subcategoria: "Aminoácidos",
    imagen: "/images/bcaa-lemon-1.jpg",
    imagenNutricional: "/images/nutricional/bcaa-lemon-nutri.jpg",
    marca: "BSN",
    precio: 44.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 0,
  },
  {
    id: 13,
    nombre: "Glutamina Pura",
    descripcion:
      "L-Glutamina 100% pura para recuperación muscular y sistema inmune. 5g por porción, sin sabor, se mezcla fácilmente con cualquier bebida.",
    categoria: "Suplementos",
    subcategoria: "Aminoácidos",
    imagen: "/images/glutamine-1.jpg",
    imagenNutricional: "/images/nutricional/glutamine-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 34.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 46,
  },
  {
    id: 14,
    nombre: "Multivitamínico Deportivo Complete",
    descripcion:
      "Fórmula completa con 25 vitaminas y minerales esenciales. Especialmente diseñado para atletas. Incluye antioxidantes y adaptógenos. 60 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Multivitamínicos",
    imagen: "/images/multivitamin-complete-1.jpg",
    imagenNutricional: "/images/nutricional/multivitamin-complete-nutri.jpg",
    marca: "MuscleTech",
    precio: 29.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 72,
  },
  {
    id: 15,
    nombre: "Multivitamínico Vegano Essential",
    descripcion:
      "Multivitamínico 100% vegano con B12, D3 vegana, hierro y zinc. Cápsulas de origen vegetal. Perfecto para dietas plant-based. 90 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Multivitamínicos",
    imagen: "/images/multivitamin-vegan-1.jpg",
    imagenNutricional: "/images/nutricional/multivitamin-vegan-nutri.jpg",
    marca: "Garden of Life",
    precio: 34.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 59,
  },
  {
    id: 16,
    nombre: "Omega-3 Triple Fuerza 2400mg",
    descripcion:
      "Aceite de pescado ultra concentrado. EPA 1200mg + DHA 900mg por porción. Salud cardiovascular, cerebral y articular. Cápsulas entéricas sin reflejo.",
    categoria: "Vitaminas",
    subcategoria: "Aceites Esenciales",
    imagen: "/images/omega3-2400-1.jpg",
    imagenNutricional: "/images/nutricional/omega3-2400-nutri.jpg",
    marca: "Dymatize",
    precio: 39.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 84,
  },
  {
    id: 17,
    nombre: "Omega-3 Vegano de Algas 1000mg",
    descripcion:
      "DHA y EPA derivados de microalgas. 100% plant-based, sostenible. Salud cardiovascular y función cognitiva. Sin sabor a pescado. 60 softgels.",
    categoria: "Vitaminas",
    subcategoria: "Aceites Esenciales",
    imagen: "/images/omega3-vegan-1.jpg",
    imagenNutricional: "/images/nutricional/omega3-vegan-nutri.jpg",
    marca: "Garden of Life",
    precio: 44.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 47,
  },
  {
    id: 18,
    nombre: "Vitamina D3 + K2 5000 IU",
    descripcion:
      "Combinación sinérgica de vitamina D3 y K2 MK-7. Salud ósea, sistema inmune y cardiovascular. Fórmula de alta absorción. 120 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Vitaminas Individuales",
    imagen: "/images/vitamin-d3-k2-1.jpg",
    imagenNutricional: "/images/nutricional/vitamin-d3-k2-nutri.jpg",
    marca: "BSN",
    precio: 24.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 96,
  },
  {
    id: 19,
    nombre: "Magnesio Glicinato 400mg",
    descripcion:
      "Forma quelada de magnesio de máxima absorción. Reduce calambres musculares, mejora descanso y recuperación. Sin efectos laxantes. 90 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Minerales",
    imagen: "/images/magnesium-glycinate-1.jpg",
    imagenNutricional: "/images/nutricional/magnesium-glycinate-nutri.jpg",
    marca: "Cellucor",
    precio: 21.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 73,
  },
  {
    id: 20,
    nombre: "Zinc Picolinato 50mg",
    descripcion:
      "Zinc de alta biodisponibilidad. Soporte del sistema inmune, testosterona y recuperación. Forma quelada de fácil absorción. 100 tabletas.",
    categoria: "Vitaminas",
    subcategoria: "Minerales",
    imagen: "/images/zinc-picolinate-1.jpg",
    imagenNutricional: "/images/nutricional/zinc-picolinate-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 16.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 112,
  },
  {
    id: 21,
    nombre: "Shaker Premium 700ml",
    descripcion:
      "Vaso mezclador con bola batidora de acero inoxidable. Libre de BPA, graduación de medidas, compartimento para suplementos. A prueba de fugas.",
    categoria: "Accesorios",
    subcategoria: "Shakers",
    imagen: "/images/shaker-premium-1.jpg",
    imagenNutricional: null,
    marca: "BSN",
    precio: 12.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 156,
  },
  {
    id: 22,
    nombre: "Shaker Eléctrico USB 500ml",
    descripcion:
      "Mezclador eléctrico recargable vía USB. Mezcla perfecta en 15 segundos. Ideal para viajes. Batería de larga duración. Color negro mate.",
    categoria: "Accesorios",
    subcategoria: "Shakers",
    imagen: "/images/shaker-electric-1.jpg",
    imagenNutricional: null,
    marca: "MuscleTech",
    precio: 34.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 43,
  },
  {
    id: 23,
    nombre: "Botella Agua Aislada 1L",
    descripcion:
      "Botella térmica de acero inoxidable. Mantiene frío 24h y caliente 12h. Boca ancha, fácil limpieza. Libre de BPA. Color azul metálico.",
    categoria: "Accesorios",
    subcategoria: "Botellas",
    imagen: "/images/water-bottle-insulated-1.jpg",
    imagenNutricional: null,
    marca: "Cellucor",
    precio: 29.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 67,
  },
  {
    id: 24,
    nombre: "Botella Agua con Marcador 2.2L",
    descripcion:
      "Botella de gran capacidad con marcadores horarios motivacionales. Ayuda a cumplir metas de hidratación diaria. Plástico Tritan sin BPA. Asa de transporte.",
    categoria: "Accesorios",
    subcategoria: "Botellas",
    imagen: "/images/water-bottle-2l-1.jpg",
    imagenNutricional: null,
    marca: "Dymatize",
    precio: 19.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 89,
  },
  {
    id: 25,
    nombre: "Cinturón Levantamiento Cuero Premium",
    descripcion:
      "Cinturón de powerlifting en cuero genuino de 10mm. Hebilla de palanca de doble seguro. Soporte lumbar máximo. Tallas S-XXL.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/leather-belt-1.jpg",
    imagenNutricional: null,
    marca: "Optimum Nutrition",
    precio: 79.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 31,
  },
  {
    id: 26,
    nombre: "Cinturón Levantamiento Nylon",
    descripcion:
      "Cinturón de entrenamiento en nylon reforzado. Cierre de velcro ajustable. Más flexible que cuero. Ideal para CrossFit y entrenamiento funcional.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/nylon-belt-1.jpg",
    imagenNutricional: null,
    marca: "Garden of Life",
    precio: 39.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 58,
  },
  {
    id: 27,
    nombre: "Guantes de Entrenamiento Pro",
    descripcion:
      "Guantes con protección de palma acolchada y muñequera integrada. Material transpirable, agarre antideslizante. Tallas XS-XL. Par.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/training-gloves-1.jpg",
    imagenNutricional: null,
    marca: "BSN",
    precio: 24.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 76,
  },
  {
    id: 28,
    nombre: "Straps de Levantamiento Acolchados",
    descripcion:
      "Correas de agarre con acolchado para muñecas. Permiten levantar más peso en ejercicios de tracción. Material de nylon resistente. 50cm de largo.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/lifting-straps-1.jpg",
    imagenNutricional: null,
    marca: "MuscleTech",
    precio: 16.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 94,
  },
  {
    id: 29,
    nombre: "Muñequeras Elásticas Pro (Par)",
    descripcion:
      "Vendas elásticas para soporte de muñecas en press de banca y overhead press. 50cm de longitud, cierre con velcro. Par de muñequeras.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/wrist-wraps-1.jpg",
    imagenNutricional: null,
    marca: "Cellucor",
    precio: 18.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 81,
  },
  {
    id: 30,
    nombre: "Bandas de Resistencia Set 5 Piezas",
    descripcion:
      "Set de bandas elásticas con diferentes resistencias (5-50kg). Incluye anclaje para puerta, asas y bolsa de transporte. Látex natural duradero.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/resistance-bands-1.jpg",
    imagenNutricional: null,
    marca: "Dymatize",
    precio: 34.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 52,
  },
  {
    id: 31,
    nombre: "Mini Bandas Loop Set 4",
    descripcion:
      "Set de 4 bandas circulares para activación glúteos y piernas. Resistencias: ligera, media, fuerte, extra fuerte. Látex de alta calidad.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/loop-bands-1.jpg",
    imagenNutricional: null,
    marca: "Optimum Nutrition",
    precio: 21.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 103,
  },
  {
    id: 32,
    nombre: "Cuerda de Saltar Profesional",
    descripcion:
      "Cuerda de velocidad con rodamientos de bola. Cable de acero recubierto, mangos ergonómicos. Longitud ajustable. Ideal para cardio y calentamiento.",
    categoria: "Accesorios",
    subcategoria: "Cardio",
    imagen: "/images/jump-rope-1.jpg",
    imagenNutricional: null,
    marca: "Garden of Life",
    precio: 14.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 127,
  },
  {
    id: 33,
    nombre: "Toalla Microfibra Gym 80x40cm",
    descripcion:
      "Toalla deportiva de secado rápido y ultra absorbente. Material antibacterial, compacta y ligera. Incluye funda de transporte. Color gris.",
    categoria: "Accesorios",
    subcategoria: "Higiene",
    imagen: "/images/gym-towel-1.jpg",
    imagenNutricional: null,
    marca: "BSN",
    precio: 12.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 142,
  },
  {
    id: 34,
    nombre: "Chalk Líquido Grip Mejorado",
    descripcion:
      "Magnesio líquido de secado rápido para mejor agarre. No genera polvo, menos sucio que tiza tradicional. 250ml. Fórmula no irritante.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/liquid-chalk-1.jpg",
    imagenNutricional: null,
    marca: "MuscleTech",
    precio: 16.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 68,
  },
  {
    id: 35,
    nombre: "Rodilleras Neopreno 7mm (Par)",
    descripcion:
      "Par de rodilleras de neopreno de 7mm. Soporte para sentadillas pesadas, reduce riesgo de lesiones. Talla única ajustable.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagen: "/images/knee-sleeves-1.jpg",
    imagenNutricional: null,
    marca: "Cellucor",
    precio: 44.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 41,
  },
  {
    id: 36,
    nombre: "Proteína Hidrolizada Beef Isolate",
    descripcion:
      "Proteína aislada de carne de res hidrolizada. 100% libre de lácteos. 27g de proteína por porción, rica en creatina natural. Sabor neutro.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/beef-protein-1.jpg",
    imagenNutricional: "/images/nutricional/beef-protein-nutri.jpg",
    marca: "Dymatize",
    precio: 99.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 17,
  },
  {
    id: 37,
    nombre: "EAAs Esenciales Sandía",
    descripcion:
      "9 aminoácidos esenciales en proporción óptima. Superior a BCAAs para síntesis proteica. 0 calorías, 0 azúcar. Hidratación mejorada.",
    categoria: "Suplementos",
    subcategoria: "Aminoácidos",
    imagen: "/images/eaa-watermelon-1.jpg",
    imagenNutricional: "/images/nutricional/eaa-watermelon-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 49.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 56,
  },
  {
    id: 38,
    nombre: "L-Carnitina Líquida 3000mg",
    descripcion:
      "L-Carnitina líquida de rápida absorción. Favorece el uso de grasas como energía. Mejora rendimiento y recuperación. Sabor cítrico. 16 porciones.",
    categoria: "Suplementos",
    subcategoria: "Quemadores",
    imagen: "/images/l-carnitine-liquid-1.jpg",
    imagenNutricional: "/images/nutricional/l-carnitine-liquid-nutri.jpg",
    marca: "BSN",
    precio: 32.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 39,
  },
  {
    id: 39,
    nombre: "Quemador Termogénico Extreme",
    descripcion:
      "Fórmula termogénica avanzada con extracto de té verde, cafeína, L-carnitina y pimienta negra. Acelera metabolismo y energía. 60 cápsulas.",
    categoria: "Suplementos",
    subcategoria: "Quemadores",
    imagen: "/images/fat-burner-1.jpg",
    imagenNutricional: "/images/nutricional/fat-burner-nutri.jpg",
    marca: "MuscleTech",
    precio: 54.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 0,
  },
  {
    id: 40,
    nombre: "Proteína Vegana Chocolate Avellanas",
    descripcion:
      "Deliciosa proteína vegana sabor chocolate con avellanas. Mezcla de guisante, arroz y semillas de calabaza. 22g proteína por porción.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagen: "/images/vegan-choco-hazelnut-1.jpg",
    imagenNutricional: "/images/nutricional/vegan-choco-hazelnut-nutri.jpg",
    marca: "Garden of Life",
    precio: 84.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 33,
  },
  {
    id: 41,
    nombre: "Ashwagandha KSM-66 600mg",
    descripcion:
      "Extracto de ashwagandha certificado KSM-66. Reduce estrés y cortisol, mejora rendimiento físico y mental. Adaptógeno premium. 60 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Adaptógenos",
    imagen: "/images/ashwagandha-1.jpg",
    imagenNutricional: "/images/nutricional/ashwagandha-nutri.jpg",
    marca: "Cellucor",
    precio: 27.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 68,
  },
  {
    id: 42,
    nombre: "Melatonina 5mg Liberación Prolongada",
    descripcion:
      "Melatonina de liberación sostenida para mejor descanso nocturno. Regula ciclo de sueño, mejora recuperación. 60 tabletas vegetales.",
    categoria: "Vitaminas",
    subcategoria: "Descanso",
    imagen: "/images/melatonin-1.jpg",
    imagenNutricional: "/images/nutricional/melatonin-nutri.jpg",
    marca: "Dymatize",
    precio: 14.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 87,
  },
  {
    id: 43,
    nombre: "Glucosamina Condroitina MSM",
    descripcion:
      "Triple fórmula para salud articular. Glucosamina 1500mg, condroitina 1200mg, MSM 1000mg. Reduce dolor e inflamación articular. 90 tabletas.",
    categoria: "Vitaminas",
    subcategoria: "Salud Articular",
    imagen: "/images/glucosamine-1.jpg",
    imagenNutricional: "/images/nutricional/glucosamine-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 42.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 36,
  },
  {
    id: 44,
    nombre: "Mochila Deportiva IronFuel 35L",
    descripcion:
      "Mochila resistente con compartimentos para laptop, shaker, ropa de gym. Material impermeable. Múltiples bolsillos. Color negro con logo.",
    categoria: "Accesorios",
    subcategoria: "Bolsos",
    imagen: "/images/gym-backpack-1.jpg",
    imagenNutricional: null,
    marca: "BSN",
    precio: 59.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 28,
  },
  {
    id: 45,
    nombre: "Pastillero Semanal Organizador",
    descripcion:
      "Organizador de suplementos con 7 compartimentos diarios y 4 tomas por día. Libre de BPA, compacto y portátil. Color transparente.",
    categoria: "Accesorios",
    subcategoria: "Organización",
    imagen: "/images/pill-organizer-1.jpg",
    imagenNutricional: null,
    marca: "MuscleTech",
    precio: 11.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 103,
  },
  {
    id: 46,
    nombre: "Balanza Digital de Cocina 5kg",
    descripcion:
      "Báscula de precisión para medir porciones de suplementos y comidas. Pantalla LCD, función tara, conversión de unidades. Plataforma de acero inoxidable.",
    categoria: "Accesorios",
    subcategoria: "Organización",
    imagen: "/images/kitchen-scale-1.jpg",
    imagenNutricional: null,
    marca: "Garden of Life",
    precio: 24.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 49,
  },
  {
    id: 47,
    nombre: "Foam Roller Alta Densidad",
    descripcion:
      "Rodillo de espuma para auto-masaje y liberación miofascial. 33cm x 14cm. Superficie texturizada. Ideal para recuperación muscular.",
    categoria: "Accesorios",
    subcategoria: "Recuperación",
    imagen: "/images/foam-roller-1.jpg",
    imagenNutricional: null,
    marca: "Cellucor",
    precio: 29.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 57,
  },
  {
    id: 48,
    nombre: "Bolas de Masaje Lacrosse (Set 2)",
    descripcion:
      "Set de 2 bolas de lacrosse para terapia de puntos gatillo. Perfectas para espalda, pies y zonas específicas. Material de caucho denso.",
    categoria: "Accesorios",
    subcategoria: "Recuperación",
    imagen: "/images/massage-balls-1.jpg",
    imagenNutricional: null,
    marca: "Dymatize",
    precio: 14.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 71,
  },
  {
    id: 49,
    nombre: "Electrolitos Hidratación Avanzada",
    descripcion:
      "Mezcla de electrolitos sin azúcar con sodio, potasio, magnesio y calcio. Hidratación óptima durante entrenamientos intensos. Sabor naranja.",
    categoria: "Suplementos",
    subcategoria: "Hidratación",
    imagen: "/images/electrolytes-orange-1.jpg",
    imagenNutricional: "/images/nutricional/electrolytes-orange-nutri.jpg",
    marca: "Optimum Nutrition",
    precio: 26.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 64,
  },
  {
    id: 50,
    nombre: "Intra-Workout Carbohidratos Ciclodextrina",
    descripcion:
      "Carbohidratos altamente ramificados de absorción rápida. Energía sostenida durante el entrenamiento sin molestias digestivas. 1kg, sin sabor.",
    categoria: "Suplementos",
    subcategoria: "Energía",
    imagen: "/images/cluster-dextrin-1.jpg",
    imagenNutricional: "/images/nutricional/cluster-dextrin-nutri.jpg",
    marca: "BSN",
    precio: 54.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 26,
  },
];
