export const DUMMY_PRODUCTS = [
  {
    id: 1,
    nombre: "Whey Protein Isolate Chocolate",
    descripcion:
      "Proteína de suero aislada de alta pureza con 90% de contenido proteico. Perfecta para la recuperación muscular post-entrenamiento. Baja en grasas y carbohidratos, ideal para definición muscular.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: [
      "/images/whey-isolate-chocolate-1.jpg",
      "/images/whey-isolate-chocolate-2.jpg",
      "/images/whey-isolate-chocolate-3.jpg",
    ],
    precio: 89.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 45,
  },
  {
    id: 2,
    nombre: "Whey Protein Isolate Vainilla",
    descripcion:
      "Proteína de suero aislada con delicioso sabor a vainilla. 25g de proteína por porción, absorción rápida y aminoácidos esenciales para máximo rendimiento.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: [
      "/images/whey-isolate-vanilla-1.jpg",
      "/images/whey-isolate-vanilla-2.jpg",
    ],
    precio: 89.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 32,
  },
  {
    id: 3,
    nombre: "Whey Protein Concentrate Fresa",
    descripcion:
      "Proteína concentrada de suero con excelente relación calidad-precio. 80% de proteína, perfecta para el crecimiento muscular y recuperación diaria.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: [
      "/images/whey-concentrate-strawberry-1.jpg",
      "/images/whey-concentrate-strawberry-2.jpg",
      "/images/whey-concentrate-strawberry-3.jpg",
    ],
    precio: 64.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 0,
  },
  {
    id: 4,
    nombre: "Proteína Vegana de Guisante y Arroz",
    descripcion:
      "Mezcla premium de proteína vegetal de guisante y arroz integral. 100% plant-based con perfil completo de aminoácidos. Sin lácteos, sin gluten, sin soja.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: [
      "/images/vegan-protein-chocolate-1.jpg",
      "/images/vegan-protein-chocolate-2.jpg",
    ],
    precio: 79.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 28,
  },
  {
    id: 5,
    nombre: "Caseína Micelar Nocturna",
    descripcion:
      "Proteína de absorción lenta ideal para tomar antes de dormir. Liberación sostenida de aminoácidos durante 7-8 horas para recuperación muscular nocturna.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: [
      "/images/casein-vanilla-1.jpg",
      "/images/casein-vanilla-2.jpg",
      "/images/casein-vanilla-3.jpg",
    ],
    precio: 94.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 19,
  },
  {
    id: 6,
    nombre: "Creatina Monohidrato Micronizada",
    descripcion:
      "Creatina monohidrato 100% pura, micronizada para mejor absorción. 5g por porción. Aumenta fuerza, potencia y masa muscular magra. Sin sabor.",
    categoria: "Suplementos",
    subcategoria: "Creatinas",
    imagenes: [
      "/images/creatine-monohydrate-1.jpg",
      "/images/creatine-monohydrate-2.jpg",
    ],
    precio: 39.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 67,
  },
  {
    id: 7,
    nombre: "Creatina HCL Avanzada",
    descripcion:
      "Clorhidrato de creatina de alta concentración. Requiere menor dosis que la monohidrato, sin retención de líquidos, sin fase de carga necesaria.",
    categoria: "Suplementos",
    subcategoria: "Creatinas",
    imagenes: [
      "/images/creatine-hcl-1.jpg",
      "/images/creatine-hcl-2.jpg",
      "/images/creatine-hcl-3.jpg",
    ],
    precio: 54.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 41,
  },
  {
    id: 8,
    nombre: "Ganador de Masa Extreme 5000",
    descripcion:
      "Fórmula hipercalórica con 1250 calorías por porción. 50g de proteína, carbohidratos complejos, MCTs y creatina. Ideal para ectomorfos y bulking.",
    categoria: "Suplementos",
    subcategoria: "Ganadores de Masa",
    imagenes: [
      "/images/mass-gainer-chocolate-1.jpg",
      "/images/mass-gainer-chocolate-2.jpg",
    ],
    precio: 119.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 23,
  },
  {
    id: 9,
    nombre: "Ganador de Masa Lean Gainer",
    descripcion:
      "Ganador de masa magra con menor contenido calórico. 750 calorías por porción, 40g de proteína, carbohidratos de bajo índice glucémico.",
    categoria: "Suplementos",
    subcategoria: "Ganadores de Masa",
    imagenes: [
      "/images/lean-gainer-vanilla-1.jpg",
      "/images/lean-gainer-vanilla-2.jpg",
      "/images/lean-gainer-vanilla-3.jpg",
    ],
    precio: 99.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 0,
  },
  {
    id: 10,
    nombre: "Ganador de Masa Vegano",
    descripcion:
      "Fórmula plant-based para aumento de masa muscular. 1100 calorías, 45g de proteína vegetal, carbohidratos de avena y quinoa. Sin lácteos ni soja.",
    categoria: "Suplementos",
    subcategoria: "Ganadores de Masa",
    imagenes: [
      "/images/vegan-mass-gainer-1.jpg",
      "/images/vegan-mass-gainer-2.jpg",
    ],
    precio: 129.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 12,
  },
  {
    id: 11,
    nombre: "Pre-Workout Explosive Energy",
    descripcion:
      "Pre-entreno con cafeína, beta-alanina, citrulina malato y taurina. Energía explosiva, mejor bombeo muscular y enfoque mental. Sabor frutas tropicales.",
    categoria: "Suplementos",
    subcategoria: "Pre-Workout",
    imagenes: [
      "/images/preworkout-tropical-1.jpg",
      "/images/preworkout-tropical-2.jpg",
      "/images/preworkout-tropical-3.jpg",
    ],
    precio: 49.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 54,
  },
  {
    id: 12,
    nombre: "BCAAs 2:1:1 Limón",
    descripcion:
      "Aminoácidos ramificados en proporción óptima 2:1:1. Previene el catabolismo muscular, acelera la recuperación. 5g por porción, sin azúcar.",
    categoria: "Suplementos",
    subcategoria: "Aminoácidos",
    imagenes: ["/images/bcaa-lemon-1.jpg", "/images/bcaa-lemon-2.jpg"],
    precio: 44.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 0,
  },
  {
    id: 13,
    nombre: "Glutamina Pura",
    descripcion:
      "L-Glutamina 100% pura para recuperación muscular y sistema inmune. 5g por porción, sin sabor, se mezcla fácilmente con cualquier bebida.",
    categoria: "Suplementos",
    subcategoria: "Aminoácidos",
    imagenes: [
      "/images/glutamine-1.jpg",
      "/images/glutamine-2.jpg",
      "/images/glutamine-3.jpg",
    ],
    precio: 34.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 46,
  },
  {
    id: 14,
    nombre: "Multivitamínico Deportivo Complete",
    descripcion:
      "Fórmula completa con 25 vitaminas y minerales esenciales. Especialmente diseñado para atletas. Incluye antioxidantes y adaptógenos. 60 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Multivitamínicos",
    imagenes: [
      "/images/multivitamin-complete-1.jpg",
      "/images/multivitamin-complete-2.jpg",
    ],
    precio: 29.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 72,
  },
  {
    id: 15,
    nombre: "Multivitamínico Vegano Essential",
    descripcion:
      "Multivitamínico 100% vegano con B12, D3 vegana, hierro y zinc. Cápsulas de origen vegetal. Perfecto para dietas plant-based. 90 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Multivitamínicos",
    imagenes: [
      "/images/multivitamin-vegan-1.jpg",
      "/images/multivitamin-vegan-2.jpg",
      "/images/multivitamin-vegan-3.jpg",
    ],
    precio: 34.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 51,
  },
  {
    id: 16,
    nombre: "Vitamina D3 5000 UI",
    descripcion:
      "Vitamina D3 de alta potencia para salud ósea, función inmune y niveles óptimos de testosterona. 120 cápsulas softgel.",
    categoria: "Vitaminas",
    subcategoria: "Vitaminas Individuales",
    imagenes: ["/images/vitamin-d3-1.jpg", "/images/vitamin-d3-2.jpg"],
    precio: 19.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 83,
  },
  {
    id: 17,
    nombre: "Omega-3 Triple Fuerza",
    descripcion:
      "Aceite de pescado ultra concentrado con EPA y DHA. Apoya salud cardiovascular, cerebral y articular. Sin sabor a pescado. 120 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Ácidos Grasos",
    imagenes: [
      "/images/omega3-1.jpg",
      "/images/omega3-2.jpg",
      "/images/omega3-3.jpg",
    ],
    precio: 39.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 44,
  },
  {
    id: 18,
    nombre: "Vitamina C 1000mg",
    descripcion:
      "Ácido ascórbico de liberación prolongada. Potente antioxidante, fortalece sistema inmune y apoya la síntesis de colágeno. 100 tabletas.",
    categoria: "Vitaminas",
    subcategoria: "Vitaminas Individuales",
    imagenes: ["/images/vitamin-c-1.jpg", "/images/vitamin-c-2.jpg"],
    precio: 16.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 91,
  },
  {
    id: 19,
    nombre: "Magnesio Quelado 400mg",
    descripcion:
      "Magnesio de alta biodisponibilidad. Esencial para función muscular, energía y descanso. Reduce calambres y fatiga. 90 cápsulas vegetales.",
    categoria: "Vitaminas",
    subcategoria: "Minerales",
    imagenes: ["/images/magnesium-1.jpg", "/images/magnesium-2.jpg"],
    precio: 24.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 62,
  },
  {
    id: 20,
    nombre: "Zinc Picolinato 50mg",
    descripcion:
      "Zinc de máxima absorción. Apoya sistema inmune, salud hormonal y recuperación muscular. Ideal para atletas intensivos. 60 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Minerales",
    imagenes: [
      "/images/zinc-1.jpg",
      "/images/zinc-2.jpg",
      "/images/zinc-3.jpg",
    ],
    precio: 18.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 0,
  },
  {
    id: 21,
    nombre: "Complejo B de Alto Rendimiento",
    descripcion:
      "8 vitaminas B esenciales para energía y metabolismo. Con B12 metilada y ácido fólico activo. Combate fatiga y estrés. 60 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Complejos Vitamínicos",
    imagenes: ["/images/complex-b-1.jpg", "/images/complex-b-2.jpg"],
    precio: 22.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 55,
  },
  {
    id: 22,
    nombre: "Colágeno Hidrolizado con Vitamina C",
    descripcion:
      "Colágeno tipo I y III para articulaciones, piel y tejidos conectivos. Enriquecido con vitamina C y ácido hialurónico. Sabor neutro.",
    categoria: "Vitaminas",
    subcategoria: "Salud Articular",
    imagenes: ["/images/collagen-1.jpg", "/images/collagen-2.jpg"],
    precio: 44.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 34,
  },
  {
    id: 23,
    nombre: "Probióticos 50 Billones UFC",
    descripcion:
      "Fórmula avanzada con 10 cepas probióticas. Mejora digestión, absorción de nutrientes y salud inmune. 30 cápsulas de liberación retardada.",
    categoria: "Vitaminas",
    subcategoria: "Salud Digestiva",
    imagenes: [
      "/images/probiotics-1.jpg",
      "/images/probiotics-2.jpg",
      "/images/probiotics-3.jpg",
    ],
    precio: 39.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 28,
  },
  {
    id: 24,
    nombre: "Shaker IronFuel Pro 700ml",
    descripcion:
      "Shaker profesional con sistema anti-grumos, compartimento para suplementos y pastillas. Libre de BPA. Escala de medición integrada. Color negro mate.",
    categoria: "Accesorios",
    subcategoria: "Shakers",
    imagenes: [
      "/images/shaker-black-1.jpg",
      "/images/shaker-black-2.jpg",
      "/images/shaker-black-3.jpg",
    ],
    precio: 14.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 145,
  },
  {
    id: 25,
    nombre: "Shaker IronFuel Elite 900ml",
    descripcion:
      "Shaker premium de gran capacidad. Doble compartimento, mezclador metálico, aislamiento térmico. Perfecto para gainers. Color azul metálico.",
    categoria: "Accesorios",
    subcategoria: "Shakers",
    imagenes: ["/images/shaker-blue-1.jpg", "/images/shaker-blue-2.jpg"],
    precio: 19.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 98,
  },
  {
    id: 26,
    nombre: "Botella Deportiva 1 Litro",
    descripcion:
      "Botella deportiva con marcadores de tiempo para recordar hidratación. Boquilla deportiva a prueba de fugas. Libre de BPA. Color transparente.",
    categoria: "Accesorios",
    subcategoria: "Botellas",
    imagenes: ["/images/bottle-1l-1.jpg", "/images/bottle-1l-2.jpg"],
    precio: 12.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 167,
  },
  {
    id: 27,
    nombre: "Botella Térmica Acero Inoxidable 750ml",
    descripcion:
      "Botella de acero inoxidable con aislamiento de doble pared. Mantiene frío 24h y caliente 12h. Boca ancha. Color gris oscuro.",
    categoria: "Accesorios",
    subcategoria: "Botellas",
    imagenes: [
      "/images/thermal-bottle-1.jpg",
      "/images/thermal-bottle-2.jpg",
      "/images/thermal-bottle-3.jpg",
    ],
    precio: 29.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 0,
  },
  {
    id: 28,
    nombre: "Cuerda para Saltar Profesional",
    descripcion:
      "Cuerda de velocidad con rodamientos de bolas y cable de acero recubierto. Mangos ergonómicos antideslizantes. Longitud ajustable.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: ["/images/jump-rope-1.jpg", "/images/jump-rope-2.jpg"],
    precio: 17.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 84,
  },
  {
    id: 29,
    nombre: "Colchoneta Yoga/Fitness Premium",
    descripcion:
      "Colchoneta NBR de alta densidad 10mm. Antideslizante, extra acolchada, con correa de transporte. 183cm x 61cm. Color morado.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: [
      "/images/yoga-mat-purple-1.jpg",
      "/images/yoga-mat-purple-2.jpg",
      "/images/yoga-mat-purple-3.jpg",
    ],
    precio: 34.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 52,
  },
  {
    id: 30,
    nombre: "Bandas de Resistencia Set 5 Niveles",
    descripcion:
      "Set de 5 bandas elásticas de resistencia (5-50kg). Incluye anclaje de puerta, manijas y bolsa de transporte. Látex natural premium.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: [
      "/images/resistance-bands-1.jpg",
      "/images/resistance-bands-2.jpg",
    ],
    precio: 39.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 47,
  },
  {
    id: 31,
    nombre: "Guantes de Entrenamiento Pro",
    descripcion:
      "Guantes acolchados para levantamiento de pesas. Palma reforzada, muñequera de soporte, material transpirable. Talla M/L/XL.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: [
      "/images/gym-gloves-1.jpg",
      "/images/gym-gloves-2.jpg",
      "/images/gym-gloves-3.jpg",
    ],
    precio: 24.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 0,
  },
  {
    id: 32,
    nombre: "Cinturón de Levantamiento 4 Pulgadas",
    descripcion:
      "Cinturón de piel sintética de alta resistencia. Hebilla de doble cierre, soporte lumbar reforzado. Ideal para sentadillas y peso muerto.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: ["/images/lifting-belt-1.jpg", "/images/lifting-belt-2.jpg"],
    precio: 49.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 31,
  },
  {
    id: 33,
    nombre: "Toalla de Microfibra Deportiva",
    descripcion:
      "Toalla ultra absorbente de secado rápido. Compacta y ligera. Perfecta para el gimnasio. 80cm x 40cm. Color gris con logo IronFuel.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: ["/images/gym-towel-1.jpg", "/images/gym-towel-2.jpg"],
    precio: 9.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 124,
  },
  {
    id: 34,
    nombre: "Straps de Levantamiento Acolchados",
    descripcion:
      "Correas para muñecas reforzadas con neopreno acolchado. Mejoran agarre en peso muerto, remo y dominadas. Par incluido.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: [
      "/images/lifting-straps-1.jpg",
      "/images/lifting-straps-2.jpg",
      "/images/lifting-straps-3.jpg",
    ],
    precio: 16.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 78,
  },
  {
    id: 35,
    nombre: "Rodilleras de Compresión 7mm",
    descripcion:
      "Par de rodilleras de neopreno de 7mm. Soporte para sentadillas pesadas, reduce riesgo de lesiones. Talla única ajustable.",
    categoria: "Accesorios",
    subcategoria: "Entrenamiento",
    imagenes: ["/images/knee-sleeves-1.jpg", "/images/knee-sleeves-2.jpg"],
    precio: 44.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 41,
  },
  {
    id: 36,
    nombre: "Proteína Hidrolizada Beef Isolate",
    descripcion:
      "Proteína aislada de carne de res hidrolizada. 100% libre de lácteos. 27g de proteína por porción, rica en creatina natural. Sabor neutro.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: ["/images/beef-protein-1.jpg", "/images/beef-protein-2.jpg"],
    precio: 99.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 17,
  },
  {
    id: 37,
    nombre: "EAAs Esenciales Sandía",
    descripcion:
      "9 aminoácidos esenciales en proporción óptima. Superior a BCAAs para síntesis proteica. 0 calorías, 0 azúcar. Hidratación mejorada.",
    categoria: "Suplementos",
    subcategoria: "Aminoácidos",
    imagenes: [
      "/images/eaa-watermelon-1.jpg",
      "/images/eaa-watermelon-2.jpg",
      "/images/eaa-watermelon-3.jpg",
    ],
    precio: 49.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 56,
  },
  {
    id: 38,
    nombre: "L-Carnitina Líquida 3000mg",
    descripcion:
      "L-Carnitina líquida de rápida absorción. Favorece el uso de grasas como energía. Mejora rendimiento y recuperación. Sabor cítrico. 16 porciones.",
    categoria: "Suplementos",
    subcategoria: "Quemadores",
    imagenes: [
      "/images/l-carnitine-liquid-1.jpg",
      "/images/l-carnitine-liquid-2.jpg",
    ],
    precio: 32.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 39,
  },
  {
    id: 39,
    nombre: "Quemador Termogénico Extreme",
    descripcion:
      "Fórmula termogénica avanzada con extracto de té verde, cafeína, L-carnitina y pimienta negra. Acelera metabolismo y energía. 60 cápsulas.",
    categoria: "Suplementos",
    subcategoria: "Quemadores",
    imagenes: ["/images/fat-burner-1.jpg", "/images/fat-burner-2.jpg"],
    precio: 54.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 25,
    stock: 0,
  },
  {
    id: 40,
    nombre: "Proteína Vegana Chocolate Avellanas",
    descripcion:
      "Deliciosa proteína vegana sabor chocolate con avellanas. Mezcla de guisante, arroz y semillas de calabaza. 22g proteína por porción.",
    categoria: "Suplementos",
    subcategoria: "Proteínas",
    imagenes: [
      "/images/vegan-choco-hazelnut-1.jpg",
      "/images/vegan-choco-hazelnut-2.jpg",
      "/images/vegan-choco-hazelnut-3.jpg",
    ],
    precio: 84.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 33,
  },
  {
    id: 41,
    nombre: "Ashwagandha KSM-66 600mg",
    descripcion:
      "Extracto de ashwagandha certificado KSM-66. Reduce estrés y cortisol, mejora rendimiento físico y mental. Adaptógeno premium. 60 cápsulas.",
    categoria: "Vitaminas",
    subcategoria: "Adaptógenos",
    imagenes: ["/images/ashwagandha-1.jpg", "/images/ashwagandha-2.jpg"],
    precio: 27.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 68,
  },
  {
    id: 42,
    nombre: "Melatonina 5mg Liberación Prolongada",
    descripcion:
      "Melatonina de liberación sostenida para mejor descanso nocturno. Regula ciclo de sueño, mejora recuperación. 60 tabletas vegetales.",
    categoria: "Vitaminas",
    subcategoria: "Descanso",
    imagenes: ["/images/melatonin-1.jpg", "/images/melatonin-2.jpg"],
    precio: 14.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 87,
  },
  {
    id: 43,
    nombre: "Glucosamina Condroitina MSM",
    descripcion:
      "Triple fórmula para salud articular. Glucosamina 1500mg, condroitina 1200mg, MSM 1000mg. Reduce dolor e inflamación articular. 90 tabletas.",
    categoria: "Vitaminas",
    subcategoria: "Salud Articular",
    imagenes: [
      "/images/glucosamine-1.jpg",
      "/images/glucosamine-2.jpg",
      "/images/glucosamine-3.jpg",
    ],
    precio: 42.99,
    vegano: false,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 36,
  },
  {
    id: 44,
    nombre: "Mochila Deportiva IronFuel 35L",
    descripcion:
      "Mochila resistente con compartimentos para laptop, shaker, ropa de gym. Material impermeable. Múltiples bolsillos. Color negro con logo.",
    categoria: "Accesorios",
    subcategoria: "Bolsos",
    imagenes: ["/images/gym-backpack-1.jpg", "/images/gym-backpack-2.jpg"],
    precio: 59.99,
    vegano: false,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 28,
  },
  {
    id: 45,
    nombre: "Pastillero Semanal Organizador",
    descripcion:
      "Organizador de suplementos con 7 compartimentos diarios y 4 tomas por día. Libre de BPA, compacto y portátil. Color transparente.",
    categoria: "Accesorios",
    subcategoria: "Organización",
    imagenes: ["/images/pill-organizer-1.jpg", "/images/pill-organizer-2.jpg"],
    precio: 11.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 103,
  },
  {
    id: 46,
    nombre: "Balanza Digital de Cocina 5kg",
    descripcion:
      "Báscula de precisión para medir porciones de suplementos y comidas. Pantalla LCD, función tara, conversión de unidades. Plataforma de acero inoxidable.",
    categoria: "Accesorios",
    subcategoria: "Organización",
    imagenes: [
      "/images/kitchen-scale-1.jpg",
      "/images/kitchen-scale-2.jpg",
      "/images/kitchen-scale-3.jpg",
    ],
    precio: 24.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 10,
    stock: 49,
  },
  {
    id: 47,
    nombre: "Foam Roller Alta Densidad",
    descripcion:
      "Rodillo de espuma para auto-masaje y liberación miofascial. 33cm x 14cm. Superficie texturizada. Ideal para recuperación muscular.",
    categoria: "Accesorios",
    subcategoria: "Recuperación",
    imagenes: ["/images/foam-roller-1.jpg", "/images/foam-roller-2.jpg"],
    precio: 29.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 57,
  },
  {
    id: 48,
    nombre: "Bolas de Masaje Lacrosse (Set 2)",
    descripcion:
      "Set de 2 bolas de lacrosse para terapia de puntos gatillo. Perfectas para espalda, pies y zonas específicas. Material de caucho denso.",
    categoria: "Accesorios",
    subcategoria: "Recuperación",
    imagenes: ["/images/massage-balls-1.jpg", "/images/massage-balls-2.jpg"],
    precio: 14.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 15,
    stock: 71,
  },
  {
    id: 49,
    nombre: "Electrolitos Hidratación Avanzada",
    descripcion:
      "Mezcla de electrolitos sin azúcar con sodio, potasio, magnesio y calcio. Hidratación óptima durante entrenamientos intensos. Sabor naranja.",
    categoria: "Suplementos",
    subcategoria: "Hidratación",
    imagenes: [
      "/images/electrolytes-orange-1.jpg",
      "/images/electrolytes-orange-2.jpg",
    ],
    precio: 26.99,
    vegano: true,
    descuento: false,
    porcentajeDescuento: 0,
    stock: 64,
  },
  {
    id: 50,
    nombre: "Intra-Workout Carbohidratos Ciclodextrina",
    descripcion:
      "Carbohidratos altamente ramificados de absorción rápida. Energía sostenida durante el entrenamiento sin molestias digestivas. 1kg, sin sabor.",
    categoria: "Suplementos",
    subcategoria: "Energía",
    imagenes: [
      "/images/cluster-dextrin-1.jpg",
      "/images/cluster-dextrin-2.jpg",
      "/images/cluster-dextrin-3.jpg",
    ],
    precio: 54.99,
    vegano: true,
    descuento: true,
    porcentajeDescuento: 20,
    stock: 26,
  },
];
